environment:
  matrix:
    - RUST_VERSION: 1.4.0
    - RUST_VERSION: beta
    - RUST_VERSION: nightly
    - TARGET: x86_64-pc-windows-msvc
    # XXX Only for nightly as of 1.4.0 stable release
    #- TARGET: i686-pc-windows-msvc
    - TARGET: i686-pc-windows-gnu
    - TARGET: x86_64-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:TARGET}.exe" -FileName "rust-installer.exe"
  - ps: .\rust-installer.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV
build: false
test_script:
  - cargo test --verbose
