environment:
  matrix:
    - RUST_VERSION: 1.4.0
      TARGET: x86_64-pc-windows-msvc
    - RUST_VERSION: 1.4.0
      TARGET: x86_64-pc-windows-gnu
    - RUST_VERSION: 1.4.0
      TARGET: i686-pc-windows-gnu
    - RUST_VERSION: beta
      TARGET: x86_64-pc-windows-msvc
    - RUST_VERSION: beta
      TARGET: x86_64-pc-windows-gnu
    - RUST_VERSION: beta
      TARGET: i686-pc-windows-gnu
    allow_failures:
      - RUST_VERSION: nightly
        TARGET: x86_64-pc-windows-msvc
      - RUST_VERSION: nightly
        TARGET: x86_64-pc-windows-gnu
      - RUST_VERSION: nightly
        TARGET: i686-pc-windows-msvc
      - RUST_VERSION: nightly
        TARGET: i686-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:TARGET}.exe" -FileName "rust-installer.exe"
  - ps: .\rust-installer.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV
build: false
test_script:
  - cargo test --verbose
