sudo: false
language: rust

# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # needed for --verify

os:
  - linux
  - osx

cache:
  apt: true
  directories:
    - target/debug/build
    - target/debug/deps
    - $HOME/.cargo

rust:
  - nightly
  - beta
  - stable

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH
      if test "$TRAVIS_RUST_VERSION" = "nightly"; then
        cargo install --git=https://github.com/arcnmx/cargo-clippy
      fi

# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      (if test "$TRAVIS_OS_NAME" = "linux"; then travis-cargo --only stable doc; fi)
  - |
      if test "$TRAVIS_RUST_VERSION" = "nightly"; then
        cargo clippy --features=$TRAVIS_CARGO_NIGHTLY_FEATURE -- -Wclippy_pedantic
      fi
after_success:
  # upload the documentation from the build with stable (automatically only actually
  # runs on the master branch, not individual PRs)
  - if test "$TRAVIS_OS_NAME" = "linux"; then travis-cargo --only stable doc-upload; fi
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  - travis-cargo coveralls --no-sudo --verify

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE='lint'
    # encrypted github token for doc upload
    - secure: "MP9oviNLDqK73nD3al+rGnrFnyhgSLFK9OhzCLNxzOhNieE9LDW4VJ+crIiUI62TPimx/nrMPYQssVQW9yivM+YWBiSjK/IDmGJrX1+xUN9XlQemKIlv+Ms1eTfzoRMcraiPILCBNc0OhqwCferHQhxEjzXpmUAjFmt8Qgb4vpdGxhvLU1f3dRk6fwIQgLsfKIqXzHczfQmGJ2eF76PLgaUtL4IYP3ogmtmOid7UD/4FEAsDcr+UNSza4u0ABRz8lEe6JCPEARQvETaKMuih21qxFnQubWiJGnH8r6p5Zvo+MDz/I5L9bLia1MCH1gUXtjzaV2naB5ozcMANZYsjvUkrSvCRn9bcccNUXNizNRWR8aQgFmytif+2uTQ8F8nDb3hg0/Et6mzroXmBPzm0B0AlV3SiAvW1odS/9WBXOATM7KRrxRgfD/R+65vWrYAgPFupvmPYXCR4mr96AgZMoU3lHjf8dIk5EyVK1rJJMtvIBQovgPDCjVhVoNh5Wyp5dG2uAH7LC18iokKt4mxfI5IEcPw94y4wodHgwn1Z0hTgBvxnwmZm1QZkOZpqAVJgSt2soZXw2n1WbEwskV39l+XNJOZ3lxKcdIxW2xY+NXLJy9sQ7nXekYHizXZb7EeD5TQWENIN9Cf6NLf8J7Z3IU4wG66gi0/HlJdfsvmAujQ="
