[package]
name = "guardhaus"
version = "0.0.5"
authors = ["Mark Lee"]
description = "An HTTP authentication/authorization library."
documentation = "https://malept.github.io/guardhaus/"
repository = "https://github.com/malept/guardhaus"
readme = "README.md"
keywords = ["http", "hyper", "authentication", "authorization", "digest"]
license = "MIT"

[dependencies]
getopts = "0.2"
hyper = "0.7"
rpassword = "0.1"
rust-crypto = "0.2"
rustc-serialize = "0.3"
unicase = "1.0"
url = "0.5"
