[package]
name = "guardhaus"
version = "0.0.15"
authors = ["Mark Lee"]
description = "An HTTP authentication/authorization library."
documentation = "https://malept.github.io/guardhaus/"
repository = "https://github.com/malept/guardhaus"
readme = "README.md"
keywords = ["http", "hyper", "authentication", "authorization", "digest"]
license = "MIT"

[features]

lint = ["clippy"]

[dependencies]
crypto-hash = "0.1"
getopts = "0.2"
hex = "0.2"
rpassword = "0.3"
unicase = "1.0"
url = "1.0"

clippy = { version = "0.0", optional = true }

[dependencies.hyper]
version = "0.9"
# SSL is not needed, so minimize the number of dependencies
default-features = false
