[package]
name = "guardhaus"
version = "0.0.9"
authors = ["Mark Lee"]
description = "An HTTP authentication/authorization library."
documentation = "https://malept.github.io/guardhaus/"
repository = "https://github.com/malept/guardhaus"
readme = "README.md"
keywords = ["http", "hyper", "authentication", "authorization", "digest"]
license = "MIT"

[features]

lint = ["clippy"]

[dependencies]
getopts = "0.2"
hyper = "0.8"
openssl = "0.7"
rpassword = "0.2"
rustc-serialize = "0.3"
unicase = "1.0"
url = "0.5"

clippy = { version = "*", optional = true }
