[package]
name = "guardhaus"
version = "0.0.7"
authors = ["Mark Lee"]
description = "An HTTP authentication/authorization library."
documentation = "https://malept.github.io/guardhaus/"
repository = "https://github.com/malept/guardhaus"
readme = "README.md"
keywords = ["http", "hyper", "authentication", "authorization", "digest"]
license = "MIT"

[features]

lint = ["clippy"]

[dependencies]
getopts = "0.2"
# TODO remove git reference when > 0.7.1 is released
hyper = { git = "https://github.com/hyperium/hyper", version = "0.7, >= 0.7.1" }
rpassword = "0.1"
rust-crypto = "0.2"
rustc-serialize = "0.3"
unicase = "1.0"
url = "0.5"

clippy = { version = "*", optional = true }
