[package]
name = "guardhaus"
version = "0.0.4"
authors = ["Mark Lee"]
description = "An HTTP authentication/authorization library."
documentation = "https://malept.github.io/guardhaus/"
repository = "https://github.com/malept/guardhaus"
readme = "README.md"
keywords = ["http", "hyper", "authentication", "authorization", "digest"]
license = "MIT"

[dependencies]
hyper = "0.7.0"
rust-crypto = "0.2.34"
rustc-serialize = "0.3.16"
unicase = "1.0.0"
url = "0.2.37"
